USE HowKteam
GO
SELECT * FROM dbo.NGUOITHAN
GO
SELECT a.HOTEN,b.TEN FROM dbo.GIAOVIEN a JOIN dbo.NGUOITHAN b ON b.MAGV = a.MAGV 
GO
SELECT * FROM dbo.NGUOITHAN
GO
SELECT * FROM dbo.GIAOVIEN
GO
CREATE INDEX index_name ON dbo.NGUOITHAN(MAGV)
GO
CREATE INDEX index_name ON dbo.GIAOVIEN(MAGV)
GO
SELECT * FROM dbo.NGUOITHAN LEFT JOIN dbo.GIAOVIEN ON GIAOVIEN.MAGV = NGUOITHAN.MAGV WHERE GIAOVIEN.MAGV='001'
GO
SELECT * INTO table_name FROM dbo.BOMON
GO 
SELECT * FROM table_name
GO
SELECT * FROM dbo.DETAI 
GO
SELECT * FROM dbo.GIAOVIEN WHERE PHAI = N'Nữ'
GO

